export const pets = [
  {
    id: 1,
    nome: "Amelia",
    peso: "5kg",
    idadeAproximada: "3 meses",
    microchip: "963003100143246",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Femea",
    caracteristica: "Pelo curto e olhos verdes",
    local: "Petz Salvador Paralela, SALVADOR, BA",
    sobre: "Dócil e sociável",
    imagem: "/assets/adote/gato-1.jpeg",
  },
  {
    id: 2,
    nome: "Thor",
    peso: "10kg",
    idadeAproximada: "6 meses",
    microchip: "963003100152789",
    especie: "Cachorro",
    porte: "M",
    raca: "SRD - Med",
    sexo: "Macho",
    caracteristica: "Pelo longo e marrom",
    local: "Pet Shop Feliz, SÃO PAULO, SP",
    sobre: "Brincalhão e ativo",
    imagem: "/assets/adote/cao-1.jpg",
  },
  {
    id: 3,
    nome: "Luna",
    peso: "4kg",
    idadeAproximada: "4 meses",
    microchip: "963003100162534",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Femea",
    caracteristica: "Pelo cinza e olhos azuis",
    local: "Amigos dos Bichos, RIO DE JANEIRO, RJ",
    sobre: "Curiosa e carinhosa",
    imagem: "/assets/adote/gato-2.jpeg",
  },
  {
    id: 4,
    nome: "Max",
    peso: "15kg",
    idadeAproximada: "1 ano",
    microchip: "963003100173568",
    especie: "Cachorro",
    porte: "M",
    raca: "Labrador",
    sexo: "Macho",
    caracteristica: "Pelo amarelo e olhos castanhos",
    local: "Clínica PetCare, CURITIBA, PR",
    sobre: "Muito inteligente e adestrado",
    imagem: "/assets/adote/cao-2.jpeg",
  },
  {
    id: 5,
    nome: "Mia",
    peso: "3kg",
    idadeAproximada: "2 meses",
    microchip: "963003100184612",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Femea",
    caracteristica: "Pelo preto e branco",
    local: "Vet&Pet, PORTO ALEGRE, RS",
    sobre: "Sociável e brincalhona",
    imagem: "/assets/adote/gato-3.jpeg",
  },
  {
    id: 6,
    nome: "Rex",
    peso: "25kg",
    idadeAproximada: "2 anos",
    microchip: "963003100195764",
    especie: "Cachorro",
    porte: "G",
    raca: "Pastor Alemão",
    sexo: "Macho",
    caracteristica: "Pelo preto e dourado",
    local: "Petz Brasília Norte, BRASÍLIA, DF",
    sobre: "Leal e protetor",
    imagem: "/assets/adote/cao-3.jpeg",
  },
  {
    id: 7,
    nome: "Bella",
    peso: "8kg",
    idadeAproximada: "5 meses",
    microchip: "963003100206835",
    especie: "Cachorro",
    porte: "M",
    raca: "SRD - Med",
    sexo: "Femea",
    caracteristica: "Pelo liso e bege",
    local: "Pet Lovers, BELO HORIZONTE, MG",
    sobre: "Amigável e dócil",
    imagem: "/assets/adote/cao-4.jpeg",
  },
  {
    id: 8,
    nome: "Oliver",
    peso: "6kg",
    idadeAproximada: "6 meses",
    microchip: "963003100217893",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Macho",
    caracteristica: "Pelo tigrado e olhos âmbar",
    local: "Petz Centro, SÃO PAULO, SP",
    sobre: "Independente e curioso",
    imagem: "/assets/adote/gato-4.jpg",
  },
  {
    id: 9,
    nome: "Simba",
    peso: "12kg",
    idadeAproximada: "1 ano e 3 meses",
    microchip: "963003100228947",
    especie: "Cachorro",
    porte: "M",
    raca: "Golden Retriever",
    sexo: "Macho",
    caracteristica: "Pelo dourado",
    local: "Centro Veterinário Animal, RECIFE, PE",
    sobre: "Amável e muito ativo",
    imagem: "/assets/adote/cao-5.jpg",
  },
  {
    id: 10,
    nome: "Chloe",
    peso: "4kg",
    idadeAproximada: "3 meses",
    microchip: "963003100239859",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Femea",
    caracteristica: "Pelo branco e olhos verdes",
    local: "Petz Salvador Shopping, SALVADOR, BA",
    sobre: "Calma e carinhosa",
    imagem: "/assets/adote/gato-5.jpg",
  },
  {
    id: 11,
    nome: "Bruno",
    peso: "30kg",
    idadeAproximada: "3 anos",
    microchip: "963003100240914",
    especie: "Cachorro",
    porte: "G",
    raca: "Rottweiler",
    sexo: "Macho",
    caracteristica: "Pelo preto com manchas marrons",
    local: "Pet&Vet, FLORIANÓPOLIS, SC",
    sobre: "Protetor e leal",
    imagem: "/assets/adote/cao-6.jpg",
  },
  {
    id: 12,
    nome: "Jade",
    peso: "5kg",
    idadeAproximada: "4 meses",
    microchip: "963003100251826",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Femea",
    caracteristica: "Pelo longo e cinza",
    local: "Mundo Animal, GOIÂNIA, GO",
    sobre: "Muito dócil e tranquila",
    imagem: "/assets/adote/gato-6.jpeg",
  },
  {
    id: 13,
    nome: "Zeus",
    peso: "28kg",
    idadeAproximada: "2 anos",
    microchip: "963003100262781",
    especie: "Cachorro",
    porte: "G",
    raca: "Pitbull",
    sexo: "Macho",
    caracteristica: "Pelo curto e preto",
    local: "Vet Clínica, MANAUS, AM",
    sobre: "Forte e protetor",
    imagem: "/assets/adote/cao-7.jpg",
  },
  {
    id: 14,
    nome: "Nina",
    peso: "7kg",
    idadeAproximada: "7 meses",
    microchip: "963003100273638",
    especie: "Cachorro",
    porte: "M",
    raca: "SRD - Med",
    sexo: "Femea",
    caracteristica: "Pelo liso e branco com manchas marrons",
    local: "Pet Center, FORTALEZA, CE",
    sobre: "Muito enérgica e brincalhona",
    imagem: "/assets/adote/cao-8.jpeg",
  },
  {
    id: 15,
    nome: "Tom",
    peso: "6kg",
    idadeAproximada: "5 meses",
    microchip: "963003100284571",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Macho",
    caracteristica: "Pelo preto",
    local: "Petz Jardim Botânico, CURITIBA, PR",
    sobre: "Independente e afetuoso",
    imagem: "/assets/adote/gato-7.jpeg",
  },
  {
    id: 16,
    nome: "Bobby",
    peso: "20kg",
    idadeAproximada: "1 ano e 6 meses",
    microchip: "963003100295674",
    especie: "Cachorro",
    porte: "M",
    raca: "Beagle",
    sexo: "Macho",
    caracteristica: "Pelo tricolor",
    local: "Animais & Cia, BRASÍLIA, DF",
    sobre: "Curioso e brincalhão",
    imagem: "/assets/adote/cao-9.jpeg",
  },
  {
    id: 17,
    nome: "Mel",
    peso: "3kg",
    idadeAproximada: "2 meses",
    microchip: "963003100306715",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Femea",
    caracteristica: "Pelo rajado",
    local: "Petz Barra, RIO DE JANEIRO, RJ",
    sobre: "Carinhosa e tímida",
    imagem: "/assets/adote/gato-8.jpeg",
  },
  {
    id: 18,
    nome: "Fred",
    peso: "12kg",
    idadeAproximada: "8 meses",
    microchip: "963003100317659",
    especie: "Cachorro",
    porte: "M",
    raca: "Bulldog Francês",
    sexo: "Macho",
    caracteristica: "Pelo curto e branco com manchas pretas",
    local: "Dog House, SÃO PAULO, SP",
    sobre: "Divertido e sociável",
    imagem: "/assets/adote/cao-10.jpeg",
  },
  {
    id: 19,
    nome: "Laila",
    peso: "10kg",
    idadeAproximada: "1 ano",
    microchip: "963003100328743",
    especie: "Cachorro",
    porte: "M",
    raca: "SRD - Med",
    sexo: "Femea",
    caracteristica: "Pelo castanho e curto",
    local: "Animal Clinic, PORTO ALEGRE, RS",
    sobre: "Muito carinhosa",
    imagem: "/assets/adote/cao-11.jpeg",
  },
  {
    id: 20,
    nome: "Zeca",
    peso: "6kg",
    idadeAproximada: "5 meses",
    microchip: "963003100339856",
    especie: "Gato",
    porte: "P",
    raca: "SRD - Peq",
    sexo: "Macho",
    caracteristica: "Pelo laranja e olhos verdes",
    local: "Vet Care, BELO HORIZONTE, MG",
    sobre: "Curioso e independente",
    imagem: "/assets/adote/gato-9.jpeg",
  },
  {
    id: 21,
    nome: "Lulu",
    peso: "9kg",
    idadeAproximada: "10 meses",
    microchip: "963003100340987",
    especie: "Cachorro",
    porte: "M",
    raca: "Poodle",
    sexo: "Femea",
    caracteristica: "Pelo cacheado branco",
    local: "Cão & Gato, CURITIBA, PR",
    sobre: "Brincalhona e afetuosa",
    imagem: "/assets/adote/cao-12.jpeg",
  },
];

export const users = [
  {
    nomeCompleto: "Katia Silva Veloso",
    cpf: "12345678910",
    endereco: "Rua das Garças, n92, Maria da Graça, Rio de Janeiro",
    email: "katiaveloso@gmail.com",
    senha: "123456",
    agendamentos: [],
  },
  {
    nomeCompleto: "Sergio Buzaranho",
    cpf: "14991823765",
    endereco: "Rua das Garças, n92, Maria da Graça, Rio de Janeiro",
    email: "sergiobuzaranho@gmail.com",
    senha: "123456",
    agendamentos: [],
  },
  {
    nomeCompleto: "João Vitor Ferreira Lima",
    cpf: "98765432100",
    endereco: "Rua das Garças, n92, Maria da Graça, Rio de Janeiro",
    email: "joaovitor_mdk@gmail.com",
    senha: "123456",
    agendamentos: [],
  },
];
